### ISSUE TITLE
Hope to support.Net 4.5.2 version above.

### ISSUE THREAD

**Issue by honorduan** [bloritsch/DHaven.Faux#31]
I used this library in version. net 4.6.1 and found it unavailable. The AssemblyLoadContext method reported an error, hoping to support. net 4.6.

**Comment by bloritsch** [comment]
First question: are you using Visual Studio 2017 or JetBrains Rider?

DHaven.Faux is a NetStandard library, and older versions of Visual Studio don't have the tooling to support those even though Microsoft.NET 4.6.1 can link to it.  I will attempt to reproduce the problem on my own tonight.

**Comment by bloritsch** [comment]
So .Net 4.5.2 will not be supported, but I will work to get 4.6.1 and on supported (i.e. NetStandard 2.0 compatibility)

I was able to create a test project, and some of the Faux's dependencies are not loading properly.  Once I can figure out the answer I'll attempt to do an update and provide any gotcha's to a WIki page.

**Comment by bloritsch** [comment]
You'll want this in the PropertyGroup section of your csproj, but that's not the full answer.

`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

I'm getting some loader errors which seem to be the result of there being two completely different APIs to load assemblies depending on whether you are in a net core application or a net framework application.  It's this problem that is causing Faux from loading in the assemblies it needs to generate the implementation for your web services.  Shame on Microsoft for advertising an API they don't implement.

**Comment by honorduan** [comment]
I also found that the two frames are not compatible, can it be compiled according to the frame? I found the following ways to support.net under the.net platform to see if I could support both platforms perfectly. I have some code to provide that overrides the compilation method for easy reference.
 `  CSharpCodeProvider objCSharpCodeProvider=new CSharpCodeProvider();
                    ICodeCompiler objICodeCompiler = objCSharpCodeProvider.CreateCompiler();
                    CompilerParameters objCompilerParameters = new CompilerParameters();
                    objCompilerParameters.ReferencedAssemblies.Add("Dhaven.Faux.dll");
                    objCompilerParameters.ReferencedAssemblies.Add("system.net.http.dll");
                    objCompilerParameters.ReferencedAssemblies.Add("ConsoleApp1.exe");
                    objCompilerParameters.GenerateExecutable = false;
                    objCompilerParameters.GenerateInMemory = true;
                    CompilerResults cr = objICodeCompiler.CompileAssemblyFromSource(objCompilerParameters,WebServiceCompiler.CodeString);
                    generatedAssembly= cr.CompiledAssembly;`

**Comment by honorduan** [comment]
I have already made the project support the.net platform. Could you please open a branch for me to submit the code? Then, check the code for me.

**Comment by bloritsch** [comment]
Created branch [31-support-netframework](https://github.com/bloritsch/DHaven.Faux/tree/31-support-netframework) for this.

If you are OK with providing the contribution, please sign the contributor form.

**Comment by honorduan** [comment]
I don't have permission. Could you please give me permission to submit? My id is: 834223627@qq.com and user name is honorduan

**Comment by bloritsch** [comment]
I've added you to the collaborators list.  You should see an invite in your email.

**Comment by honorduan** [comment]
I have submitted my code and please  review my code.

**Comment by bloritsch** [comment]
Sorry it's taking so long.  Had something come up where I wasn't free.  Will get to it today.

**Comment by bloritsch** [comment]
@honorduan, please sign the [Contributor License Agreement](https://www.clahub.com/agreements/bloritsch/DHaven.Faux).  That's preventing the pull request from passing.
