### ISSUE TITLE
Add support for Hystrix (Steeltoe.CircuitBreaker)

### ISSUE THREAD

**Issue by bloritsch** [bloritsch/DHaven.Faux#43]
**Describe the solution you'd like**
Add support for Hystrix (circuit breaker pattern) to improve reliability.  The circuitbreaker support should have support for fail-over to provide a default value.

As a Micro Services Developer I want to automatically have support for Hystrix so that I can improve the reliability of the systems I am building.

**Describe alternatives you've considered**
Right now, Steeltoe's offering is the only one that supports the Hystrix monitoring from the NetFlix infrastructure projects.  It's going to be more useful to be able to incorporate this into larger infrastructure.

The two real alternatives are:

* Bake this in to the core project (DHaven.Faux)
* Create a new project to extend the core (DHaven.Faux.CircuitBreaker)

I am leaning toward the second.  but I can be persuaded.

**Comment by bloritsch** [comment]
I've worked out how to generate the code for synchronous calls.  Hystrix support may force me to go async/sync/back to async.  That's definitely not the ideal way to go.  I have an [open ticket](https://github.com/SteeltoeOSS/CircuitBreaker/issues/14) on the Steeltoe GitHub project to see if I can keep it all asynchronous.

**Comment by bloritsch** [comment]
I believe I have a working workaround... testing I'll create the branch and do the testing.

**Comment by bloritsch** [comment]
Back to the drawing board.  What I have works as long as you don't have `ref` or `out` parameters.  Unit tests fail because of the `IReturnService`.  I have a separate project while I work on the generated classes to make sure that it all compiles.

**Comment by SkyvenXiong** [comment]
I have support the feign by myself use the castle aop feature. i think it is similarity as the java imp;
in the same way it is easy to imp the Hystrix use the aop ;

**Comment by SkyvenXiong** [comment]
in my case it is more difficulty .not only C#,also has java code . so i consider to use then json generated by swaager to general the java and C# code . but only general the contract not the implement.

Of course what I said may have little to do with your current project implementation.

But if I want to do something for your project, what should I do.

**Comment by bloritsch** [comment]
If you want to help, then create new issues if you'd like to see a change.  If you want to actually implement any of the issues, then you'll need to sign the contributor's agreement, make changes in a feature branch, and when you are done make a pull request.

For this particular issue, I know where I am going, and am working through it a little at a time.
