### ISSUE TITLE
Task with no return value cannot be declared

### ISSUE THREAD

**Issue by DeepSkyJees** [bloritsch/DHaven.Faux#50]
1、The regenerated code cannot be overwritten
2、Method has no return value ，but it can not use "Task" directly.

**Comment by bloritsch** [comment]
Looks like this affects Hystrix enabled bindings only... unless I'm missing something.  I've added a couple unit tests and will be committing the update once this is fixed.

**Comment by bloritsch** [comment]
Added unit tests to recreate the error.  A return type of `void` is perfectly fine, but a return type of `Task` is not.

The bug is related to mistaking the `Task` as a convertible type, which it is not.  The generated code looks something like this:

```
        public async System.Threading.Tasks.Task<System.Threading.Tasks.Task> PingAsync()
        {
            var 仮variables = new System.Collections.Generic.Dictionary<string,object>();
            var 仮reqParams = new System.Collections.Generic.Dictionary<string,string>();
            var 仮request = CreateRequest(System.Net.Http.HttpMethod.Post, "", 仮variables, 仮reqParams);
            var 仮response = await InvokeAsync(仮request);
            return await DHaven.Faux.HttpSupport.DiscoveryAwareBase.ConvertToObjectAsync<System.Threading.Tasks.Task>(仮response);
        }
```

Will fix.
